sudo: required
services:
  - docker

before_install:
  - docker build -t gbarre2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gbarre2/react-test npm test -- --coverage

after_success:
  - docker build -t gbarre2/multi-client ./client
  - docker build -t gbarre2/multi-nginx ./nginx
  - docker build -t gbarre2/multi-server ./server
  - docker build -t gbarre2/multi-worker ./worker
  # Log in
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push gbarre2/multi-client
  - docker push gbarre2/multi-nginx
  - docker push gbarre2/multi-server
  - docker push gbarre2/multi-worker
